from __future__ import annotations

from enum import StrEnum


class TaskStatus(StrEnum):
    PENDING = "PENDING"
    PLANNING = "PLANNING"
    RUNNING = "RUNNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    RETRYING = "RETRYING"

    @property
    def is_terminal(self) -> bool:
        return self in (TaskStatus.COMPLETED, TaskStatus.FAILED, TaskStatus.CANCELLED)


RUNNABLE_STATUSES = (TaskStatus.PENDING, TaskStatus.RETRYING)
IN_FLIGHT_STATUSES = (TaskStatus.PLANNING, TaskStatus.RUNNING)


class TaskSource(StrEnum):
    WEB = "web"
    API = "api"
    TELEGRAM = "telegram"
    SCHEDULER = "scheduler"
    WEBHOOK = "webhook"


class StepStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class EventType(StrEnum):
    TASK_CREATED = "TASK_CREATED"
    TASK_CLAIMED = "TASK_CLAIMED"
    TASK_NORMALIZED = "TASK_NORMALIZED"
    MEMORY_RETRIEVED = "MEMORY_RETRIEVED"
    PLANNING_STARTED = "PLANNING_STARTED"
    PLAN_CREATED = "PLAN_CREATED"
    AGENT_SELECTED = "AGENT_SELECTED"
    STEP_STARTED = "STEP_STARTED"
    STEP_COMPLETED = "STEP_COMPLETED"
    STEP_FAILED = "STEP_FAILED"
    AGENT_STARTED = "AGENT_STARTED"
    MODEL_CALL = "MODEL_CALL"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    TOOL_CALLED = "TOOL_CALLED"
    TOOL_RESULT = "TOOL_RESULT"
    TOOL_BLOCKED = "TOOL_BLOCKED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_DECIDED = "APPROVAL_DECIDED"
    VALIDATION = "VALIDATION"
    RETRY = "RETRY"
    RECOVERED = "RECOVERED"
    ERROR = "ERROR"
    CONTEXT_COMPACTED = "CONTEXT_COMPACTED"
    REPORT_CREATED = "REPORT_CREATED"
    MEMORY_CREATED = "MEMORY_CREATED"
    FEEDBACK_RECEIVED = "FEEDBACK_RECEIVED"
    LEARNING_CANDIDATE = "LEARNING_CANDIDATE"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_CANCELLED = "TASK_CANCELLED"


class MemoryType(StrEnum):
    CORE = "CORE"
    SEMANTIC = "SEMANTIC"
    EPISODIC = "EPISODIC"
    PROCEDURAL = "PROCEDURAL"
    EVIDENCE = "EVIDENCE"


class MemoryStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    DEPRECATED = "DEPRECATED"
    ARCHIVED = "ARCHIVED"


class RiskLevel(StrEnum):
    READ = "READ"
    WRITE = "WRITE"
    DESTRUCTIVE = "DESTRUCTIVE"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ToolExecutionStatus(StrEnum):
    RUNNING = "RUNNING"            # recorded before the provider is called
    INTERRUPTED = "INTERRUPTED"    # worker died during the call: outcome unknown, never auto-re-run if mutating
    ABANDONED = "ABANDONED"        # interrupted call acknowledged by a human (manual task retry)
    SUCCESS = "SUCCESS"
    ERROR = "ERROR"
    BLOCKED = "BLOCKED"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    REJECTED = "REJECTED"
    CONFIGURATION_REQUIRED = "CONFIGURATION_REQUIRED"


class LearningStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DEPRECATED = "DEPRECATED"


class LearningCategory(StrEnum):
    PROCEDURE = "PROCEDURE"
    FACT = "FACT"
    PREFERENCE = "PREFERENCE"
    ANTI_PATTERN = "ANTI_PATTERN"
    OUTCOME = "OUTCOME"


class FeedbackRating(StrEnum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"


class ScheduleType(StrEnum):
    ONCE = "ONCE"
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    CRON = "CRON"
